//
//  OCBlank.h
//  OpenCoinWallet
//
//  Created by Gulliver on 15.01.13.
//  Copyright (c) 2013 Opencoin Team. All rights reserved.
//

#import <Foundation/Foundation.h>

@class OCCurrency;
@class OCMintKey;

@interface OCBlank : NSObject

- (id) initWithAttributes:(NSDictionary *)attributes;
- (NSDictionary*) toDictionary;


+(OCBlank*) blankWithCurrency:(OCCurrency*) currency
             WithDenomination: (NSInteger) denomination
                  WithMintKey: (OCMintKey*) mint_key;

@property(retain)  NSURL* protocol_version; // = http://opencoin.org/OpenCoinProtocol/1.0
@property(retain)  NSString* issuer_id;        // = base64(hash(public master key))
@property(retain)  NSURL* cdd_location;        // = http://opencent.net/OpenCent [[Hint to download the CDD if not available anyway. Useful for clients to "bootstrap" a yet unknown currency.]]
@property(assign)  NSInteger   denomination;   // = integer [[Only a hint, not verified value. Denomination MUST be verified by checking the mint key's denomination.]]
@property(retain)  NSString* mint_key_id;      // = base64(hash(public mint key))
@property(retain)  NSString* serial;           // = base64(128bit random number) [[This random value is generated by clients. A high entropy (crypto grade quality) is important.]]

@end
